"""initial database schema

Revision ID: 1bdeebec3d80
Revises: 
Create Date: 2026-10-07 18:25:51.431347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bdeebec3d80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'BUSINESS', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_users',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', name='business_user_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id', name='uq_business_users_business_user')
    )
    op.create_index(op.f('ix_business_users_business_id'), 'business_users', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_users_user_id'), 'business_users', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('stamp_target', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_business_id'), 'campaigns', ['business_id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_user_id'), 'customer_profiles', ['user_id'], unique=True)
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('CAMPAIGN_JOINED', 'STAMP_EARNED', 'REWARD_EARNED', 'REWARD_USED', 'QR_SCANNED', name='transaction_type'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_business_id'), 'transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('campaign_memberships',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='campaign_membership_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'customer_id', name='uq_campaign_membership_campaign_customer')
    )
    op.create_index(op.f('ix_campaign_memberships_campaign_id'), 'campaign_memberships', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_memberships_customer_id'), 'campaign_memberships', ['customer_id'], unique=False)
    op.create_table('qr_sessions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', 'CANCELLED', name='qr_session_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_sessions_business_id'), 'qr_sessions', ['business_id'], unique=False)
    op.create_index(op.f('ix_qr_sessions_customer_id'), 'qr_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_qr_sessions_token_hash'), 'qr_sessions', ['token_hash'], unique=True)
    op.create_table('rewards',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_type', sa.Enum('FREE_PRODUCT', 'DISCOUNT_PERCENT', 'DISCOUNT_AMOUNT', 'FREE_SERVICE', 'OTHER', name='reward_type'), nullable=False),
    sa.Column('reward_value', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_campaign_id'), 'rewards', ['campaign_id'], unique=True)
    op.create_table('loyalty_cards',
    sa.Column('campaign_membership_id', sa.UUID(), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('stamp_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='loyalty_card_status'), server_default='ACTIVE', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_membership_id'], ['campaign_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_membership_id', 'card_number', name='uq_loyalty_cards_membership_card_number')
    )
    op.create_index(op.f('ix_loyalty_cards_campaign_membership_id'), 'loyalty_cards', ['campaign_membership_id'], unique=False)
    op.create_table('customer_rewards',
    sa.Column('reward_id', sa.UUID(), nullable=False),
    sa.Column('loyalty_card_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'USED', 'EXPIRED', name='customer_reward_status'), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loyalty_card_id'], ['loyalty_cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loyalty_card_id', name='uq_customer_rewards_loyalty_card')
    )
    op.create_index(op.f('ix_customer_rewards_loyalty_card_id'), 'customer_rewards', ['loyalty_card_id'], unique=False)
    op.create_index(op.f('ix_customer_rewards_reward_id'), 'customer_rewards', ['reward_id'], unique=False)
    op.create_table('stamps',
    sa.Column('campaign_membership_id', sa.UUID(), nullable=False),
    sa.Column('qr_session_id', sa.UUID(), nullable=False),
    sa.Column('business_user_id', sa.UUID(), nullable=False),
    sa.Column('loyalty_card_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_user_id'], ['business_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_membership_id'], ['campaign_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loyalty_card_id'], ['loyalty_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qr_session_id'], ['qr_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stamps_business_user_id'), 'stamps', ['business_user_id'], unique=False)
    op.create_index(op.f('ix_stamps_campaign_membership_id'), 'stamps', ['campaign_membership_id'], unique=False)
    op.create_index(op.f('ix_stamps_loyalty_card_id'), 'stamps', ['loyalty_card_id'], unique=False)
    op.create_index(op.f('ix_stamps_qr_session_id'), 'stamps', ['qr_session_id'], unique=True)
    op.create_table('reward_claims',
    sa.Column('customer_reward_id', sa.UUID(), nullable=False),
    sa.Column('business_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('USED', 'CANCELLED', name='reward_claim_status'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_user_id'], ['business_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_reward_id'], ['customer_rewards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_claims_business_user_id'), 'reward_claims', ['business_user_id'], unique=False)
    op.create_index(op.f('ix_reward_claims_customer_reward_id'), 'reward_claims', ['customer_reward_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_claims_customer_reward_id'), table_name='reward_claims')
    op.drop_index(op.f('ix_reward_claims_business_user_id'), table_name='reward_claims')
    op.drop_table('reward_claims')
    op.drop_index(op.f('ix_stamps_qr_session_id'), table_name='stamps')
    op.drop_index(op.f('ix_stamps_loyalty_card_id'), table_name='stamps')
    op.drop_index(op.f('ix_stamps_campaign_membership_id'), table_name='stamps')
    op.drop_index(op.f('ix_stamps_business_user_id'), table_name='stamps')
    op.drop_table('stamps')
    op.drop_index(op.f('ix_customer_rewards_reward_id'), table_name='customer_rewards')
    op.drop_index(op.f('ix_customer_rewards_loyalty_card_id'), table_name='customer_rewards')
    op.drop_table('customer_rewards')
    op.drop_index(op.f('ix_loyalty_cards_campaign_membership_id'), table_name='loyalty_cards')
    op.drop_table('loyalty_cards')
    op.drop_index(op.f('ix_rewards_campaign_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_qr_sessions_token_hash'), table_name='qr_sessions')
    op.drop_index(op.f('ix_qr_sessions_customer_id'), table_name='qr_sessions')
    op.drop_index(op.f('ix_qr_sessions_business_id'), table_name='qr_sessions')
    op.drop_table('qr_sessions')
    op.drop_index(op.f('ix_campaign_memberships_customer_id'), table_name='campaign_memberships')
    op.drop_index(op.f('ix_campaign_memberships_campaign_id'), table_name='campaign_memberships')
    op.drop_table('campaign_memberships')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_business_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_customer_profiles_user_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_campaigns_business_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_business_users_user_id'), table_name='business_users')
    op.drop_index(op.f('ix_business_users_business_id'), table_name='business_users')
    op.drop_table('business_users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
