from enum import StrEnum


class TransactionType(StrEnum):
    CAMPAIGN_JOINED = "CAMPAIGN_JOINED"
    STAMP_EARNED = "STAMP_EARNED"
    REWARD_EARNED = "REWARD_EARNED"
    REWARD_USED = "REWARD_USED"
    QR_SCANNED = "QR_SCANNED"